name: Github Actions CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - githubactions*
      - feature/**
      - fix/**
      - pr/**



jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "TOOLSET=gcc COMPILER=g++-4.7 CXXSTD=c++11 Job 0"
            buildtype: "boost"
            packages: "g++-4.7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-4.7"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-4.7"
            cxxstd: "c++11"
            drone_job_uuid: "b6589fc6ab"
          - name: "TOOLSET=gcc COMPILER=g++-4.8 CXXSTD=c++11 Job 1"
            buildtype: "boost"
            packages: "g++-4.8"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-4.8"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-4.8"
            cxxstd: "c++11"
            drone_job_uuid: "356a192b79"
          - name: "TOOLSET=gcc COMPILER=g++-4.9 CXXSTD=c++11 Job 2"
            buildtype: "boost"
            packages: "g++-4.9"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-4.9"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-4.9"
            cxxstd: "c++11"
            drone_job_uuid: "da4b9237ba"
          - name: "TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++11 Job 3"
            buildtype: "boost"
            packages: "g++-5"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-5"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-5"
            cxxstd: "c++11"
            drone_job_uuid: "77de68daec"
          - name: "TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++14 Job 4"
            buildtype: "boost"
            packages: "g++-5"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-5"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-5"
            cxxstd: "c++14"
            drone_job_uuid: "1b64538924"
          - name: "TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++1z Job 5"
            buildtype: "boost"
            packages: "g++-5"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-5"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-5"
            cxxstd: "c++1z"
            drone_job_uuid: "ac3478d69a"
          - name: "TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++11 Job 6"
            buildtype: "boost"
            packages: "g++-6"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-6"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-6"
            cxxstd: "c++11"
            drone_job_uuid: "c1dfd96eea"
          - name: "TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++14 Job 7"
            buildtype: "boost"
            packages: "g++-6"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-6"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-6"
            cxxstd: "c++14"
            drone_job_uuid: "902ba3cda1"
          - name: "TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++1z Job 8"
            buildtype: "boost"
            packages: "g++-6"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-6"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-6"
            cxxstd: "c++1z"
            drone_job_uuid: "fe5dbbcea5"
          - name: "TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++11 Job 9"
            buildtype: "boost"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-7"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-7"
            cxxstd: "c++11"
            drone_job_uuid: "0ade7c2cf9"
          - name: "TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++14 Job 10"
            buildtype: "boost"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-7"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-7"
            cxxstd: "c++14"
            drone_job_uuid: "b1d5781111"
          - name: "TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++1z Job 11"
            buildtype: "boost"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++-7"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc"
            compiler: "g++-7"
            cxxstd: "c++1z"
            drone_job_uuid: "17ba079149"
          - name: "TOOLSET=clang COMPILER=clang++-3.5 CXXSTD=c++ Job 12"
            buildtype: "boost"
            packages: "clang-3.5"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++"
            cxxflags: ""
            sources: ""
            llvm_os: "precise"
            llvm_ver: "3.5"
            toolset: "clang"
            compiler: "clang++-3.5"
            cxxstd: "c++11"
            drone_job_uuid: "7b52009b64"
          - name: "TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=c++ Job 13"
            buildtype: "boost"
            packages: "clang-3.6"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++"
            cxxflags: ""
            sources: ""
            llvm_os: "precise"
            llvm_ver: "3.6"
            toolset: "clang"
            compiler: "clang++-3.6"
            cxxstd: "c++11"
            drone_job_uuid: "bd307a3ec3"
          - name: "TOOLSET=clang COMPILER=clang++-3.7 CXXSTD=c++ Job 14"
            buildtype: "boost"
            packages: "clang-3.7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++"
            cxxflags: ""
            sources: ""
            llvm_os: "precise"
            llvm_ver: "3.7"
            toolset: "clang"
            compiler: "clang++-3.7"
            cxxstd: "c++11"
            drone_job_uuid: "fa35e19212"
          - name: "TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=c++ Job 15"
            buildtype: "boost"
            packages: "clang-3.8"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++-3.8"
            cxxflags: ""
            sources: ""
            llvm_os: "precise"
            llvm_ver: "3.8"
            toolset: "clang"
            compiler: "clang++-3.8"
            cxxstd: "c++11"
            drone_job_uuid: "f1abd67035"
          - name: "TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++ Job 16"
            buildtype: "boost"
            packages: "clang-3.9"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++-3.9"
            cxxflags: ""
            sources: ""
            llvm_os: "precise"
            llvm_ver: "3.9"
            toolset: "clang"
            compiler: "clang++-3.9"
            cxxstd: "c++11"
            drone_job_uuid: "1574bddb75"
          - name: "TOOLSET=clang COMPILER=clang++-4.0 CXXSTD=c++ Job 17"
            buildtype: "boost"
            packages: "clang-4.0"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++-4.0"
            cxxflags: ""
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "4.0"
            toolset: "clang"
            compiler: "clang++-4.0"
            cxxstd: "c++11"
            drone_job_uuid: "0716d9708d"
          - name: "TOOLSET=clang COMPILER=clang++-4.0 CXXSTD=c++ Job 18"
            buildtype: "boost"
            packages: "clang-4.0"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++-4.0"
            cxxflags: ""
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "4.0"
            toolset: "clang"
            compiler: "clang++-4.0"
            cxxstd: "c++14"
            drone_job_uuid: "9e6a55b6b4"
          - name: "TOOLSET=clang COMPILER=clang++-4.0 CXXSTD=c++ Job 19"
            buildtype: "boost"
            packages: "clang-4.0"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "clang++-4.0"
            cxxflags: ""
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "4.0"
            toolset: "clang"
            compiler: "clang++-4.0"
            cxxstd: "c++1z"
            drone_job_uuid: "b3f0c7f6bb"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: boost
        #if: ${{ matrix.buildtype }} == boost
        if: matrix.buildtype == 'boost'
        shell: bash
        env:
          TRAVIS_BRANCH: ${{ github.base_ref }}
          CXX: ${{ matrix.cxx }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          PACKAGES_TO_REMOVE: ${{ matrix.packages_to_remove }}
          TOOLSET: ${{ matrix.toolset }}
          COMPILER: ${{ matrix.compiler }}
          CXXSTD: ${{ matrix.cxxstd }}
          DRONE_JOB_UUID: ${{ matrix.drone_job_uuid }}
        run: |
          echo '==================================> SETUP'
          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
          echo '==================================> PACKAGES'
          set -ex
          echo "Before package removal or install"
          whoami
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
          if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
          echo "about to run linux-cxx-install.sh"
          ./.github/boost-ci/ci/drone/linux-cxx-install.sh
          echo "After package removal and install"
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo '==================================> INSTALL AND COMPILE'
          . .github/scripts/boost.sh
       

  osx:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "TOOLSET=clang COMPILER=clang++ CXXSTD=c++11 Job 20"
            buildtype: "boost"
            packages: ""
            os: "macos-10.15"
            cxx: "clang++"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            xcode_version: ""
            toolset: "clang"
            compiler: "clang++"
            cxxstd: "c++11"
            drone_job_uuid: "91032ad7bb"
          - name: "TOOLSET=clang COMPILER=clang++ CXXSTD=c++14 Job 21"
            buildtype: "boost"
            packages: ""
            os: "macos-10.15"
            cxx: "clang++"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            xcode_version: ""
            toolset: "clang"
            compiler: "clang++"
            cxxstd: "c++14"
            drone_job_uuid: "472b07b9fc"
          - name: "TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z Job 22"
            buildtype: "boost"
            packages: ""
            os: "macos-10.15"
            cxx: "clang++"
            cxxflags: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            xcode_version: ""
            toolset: "clang"
            compiler: "clang++"
            cxxstd: "c++1z"
            drone_job_uuid: "12c6fc06c9"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set DEVELOPER_DIR
        if: matrix.xcode_version != ''
        run: echo "::set-env name=DEVELOPER_DIR:/Applications/Xcode-:${{ matrix.xcode_version }}.app/Contents/Developer"
      - name: Test DEVELOPER_DIR
        run: echo $DEVELOPER_DIR
      - name: boost
        #if: ${{ matrix.buildtype }} == boost
        if: matrix.buildtype == 'boost'
        shell: bash
        env:
          TRAVIS_BRANCH: ${{ github.base_ref }}
          CXX: ${{ matrix.cxx }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          TOOLSET: ${{ matrix.toolset }}
          COMPILER: ${{ matrix.compiler }}
          CXXSTD: ${{ matrix.cxxstd }}
          DRONE_JOB_UUID: ${{ matrix.drone_job_uuid }}
        run: |
          echo '==================================> SETUP'
          set -ex
          uname -a
          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && /usr/local/bin/wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
          echo '==================================> PACKAGES'
          ./.github/boost-ci/ci/drone/osx-cxx-install.sh

          echo '==================================> INSTALL AND COMPILE'
          . .github/scripts/boost.sh
       
